name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main

  lint-scss:
    name: Lint SCSS
    uses: alphagov/govuk-infrastructure/.github/workflows/stylelint.yml@main
    with:
      files: "app/assets/stylesheets/"

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Setup MongoDB
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mongodb@main
        with:
          version: 3.6

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Publishing API (for Content Schemas)
        uses: actions/checkout@v3
        with:
          repository: alphagov/publishing-api
          ref: deployed-to-production
          path: vendor/publishing-api

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

      - name: Precompile assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Initialize database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:setup

      - name: Run RSpec
        env:
          RAILS_ENV: test
          GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
        run: bundle exec rake spec

